version: "3.0"
services:
  nginx:
    build:
      context: Docker/nginx
    ports:
      - '80:80'

  postgres:
    image: postgres
    ports:
      - 2222:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
