version: "3.0"
services:

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040

  nginx:
    build:
      context: Docker/nginx
    ports:
      - '8012:80'

  postgres:
    image: postgres
    ports:
      - 2222:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
